name: test
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        perl:
          [
            "5.40",
            "5.38",
            "5.36",
            "5.34",
            "5.32",
            "5.30",
            "5.28",
            "5.26",
            "5.24",
            "5.22",
            "5.20",
            "5.18",
            "5.16",
          ]

    name: Perl ${{ matrix.perl }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup perl
        uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: ${{ matrix.perl }}

      - name: Install dependencies
        run: |
          cpm install -g Test2::V0
          cpm install -g JSON::XS
          cpm install -g JSON::PP
          cpm install -g Cpanel::JSON::XS

          cpm install -g Type::Tiny
          cpm install -g Smart::Args::TypeTiny

      - run: prove -lvr t/test.t

